"""
CalPow Engine — central configuration.

All physical parameters reference the corpus (CALPOW_CORPUS.md).
Change values here for calibration experiments; do not hardcode in pipeline modules.

Tile loading precedence (checked at app startup):
  1. outputs/  — generated by run_pipeline.py with real 3DEP data (not in git)
  2. demo_data/ — bundled synthetic Sierra Nevada tiles, used on Railway until
                  real tiles are uploaded (IS in git, ~13 MB)
"""

from pathlib import Path

# ── Paths ───────────────────────────────────────────────────────────────────
ROOT = Path(__file__).parent
DATA_DIR = ROOT / "data"
OUTPUT_DIR = ROOT / "outputs"
DEMO_DATA_DIR = ROOT / "demo_data"   # bundled fallback for Railway / cold starts
DATA_DIR.mkdir(exist_ok=True)
OUTPUT_DIR.mkdir(exist_ok=True)

def get_tile_dir() -> Path:
    """
    Return the directory that contains the precomputed terrain tiles.

    Tries outputs/ first (real pipeline run), then demo_data/ (bundled).
    The app will log which directory it's using at startup.
    """
    required = ["cost_surface.tif", "slope.tif", "dem_10m.tif"]
    if all((OUTPUT_DIR / f).exists() for f in required):
        return OUTPUT_DIR
    if all((DEMO_DATA_DIR / f).exists() for f in required):
        return DEMO_DATA_DIR
    # Neither available — return outputs/ and let app.py report the error
    return OUTPUT_DIR

# ── Test area: Carson Pass / Red Lake Peak, Sierra Nevada ───────────────────
# Site of the original Algorithmic Alpinism field test.
# WGS84 (lon_min, lat_min, lon_max, lat_max)
TEST_BBOX = (-119.95, 38.65, -119.82, 38.76)

# Demo tile bounding box (matches demo_data/ tiles generated 2026-07-01)
DEMO_BBOX = (-120.05, 38.63, -119.93, 38.72)

# DEM resolution to request (metres). 10 m is the sweet spot per corpus §1.
DEM_RESOLUTION = 10

# ── PRA (Veitinger 2016) ─────────────────────────────────────────────────────
PRA = {
    "slope_a": 10.0,
    "slope_b": 4,
    "slope_c": 38.0,
    "rough_a": 0.5,
    "rough_b": 2,
    "rough_c": 0.0,
    "min_membership": 0.1,
    "slope_min": 28.0,
    "slope_max": 60.0,
}

# ── Flow-Py (D'Amboise et al. 2022) ─────────────────────────────────────────
FLOWPY = {
    "alpha": 25.0,
    "exp": 8,
    "min_flux": 1e-4,
}

# ── Winstral Sx (Winstral & Marks 2002) ─────────────────────────────────────
SX = {
    "dmax": 300.0,
    "az_window": 25.0,
    "az_step": 5.0,
}

# ── Cost surface weights ─────────────────────────────────────────────────────
COST = {
    "effort_weight": 0.3,
    "hazard_weight": 0.7,
    "w_pra": 0.30,
    "w_zdelta": 0.30,
    "w_cell_counts": 0.20,
    "w_sx": 0.20,
    "slope_k": 0.002,
    "danger_multiplier": 2.0,
}

# ── Solar (pvlib + WhiteboxTools) ────────────────────────────────────────────
SOLAR = {
    "tz": "America/Los_Angeles",
    "hours": [9, 11, 13, 15],
}
